In [2]:
import pandas as pd

## 1. concat()을 사용하여 df1과 df2를 행 방향으로 결합하시오.

In [8]:
df1 = pd.DataFrame({
    "이름": ["김민준", "이서연", "박지훈"],
    "점수": [85, 90, 75]
})

df2 = pd.DataFrame({
    "이름": ["최유진", "정현우", "강수빈"],
    "점수": [95, 80, 88]
})

In [9]:
df3 = pd.concat([df1, df2], axis=0, ignore_index=True)
df3

    이름  점수
0  김민준  85
1  이서연  90
2  박지훈  75
3  최유진  95
4  정현우  80
5  강수빈  88

## ​2. 두 DataFrame을 열 방향으로 결합하시오.

In [10]:
df1 = pd.DataFrame({
    "이름": ["김민준", "이서연", "박지훈"],
    "점수": [85, 90, 75]
})

df2 = pd.DataFrame({
    "이름": ["최유진", "정현우", "강수빈"],
    "등급": ["B", "A", "C"]
})

In [12]:
df4 = pd.concat([df1, df2], axis=1)
df4

    이름  점수   이름 등급
0  김민준  85  최유진  B
1  이서연  90  정현우  A
2  박지훈  75  강수빈  C

## 3. 학생ID를 기준으로 두 DataFrame을 결합하시오.

In [13]:
students = pd.DataFrame({
    "학생ID": [101, 102, 103, 104],
    "이름": ["김민준", "이서연", "박지훈", "최유진"]
})

scores = pd.DataFrame({
    "학생ID": [101, 102, 103, 104],
    "점수": [85, 90, 75, 95]
})

In [16]:
result = pd.merge(
    students,
    scores,
    on="학생ID",
    how="inner"
)

result

   학생ID   이름  점수
0   101  김민준  85
1   102  이서연  90
2   103  박지훈  75
3   104  최유진  95

## ​4. 고객ID를 기준으로 두 DataFrame을 merge()하시오.
(결과에 다음 컬럼이 포함되도록 하시오.)

In [17]:
customer = pd.DataFrame({
    "고객ID": [1, 2, 3],
    "이름": ["김민준", "이서연", "박지훈"]
})

order = pd.DataFrame({
    "고객ID": [1, 2, 3],
    "상품": ["노트북", "마우스", "키보드"],
    "금액": [1200000, 30000, 80000]
})

In [19]:
result2 = pd.merge(
    customer,
    order,
    on="고객ID",
    how="outer"
)

result2

   고객ID   이름   상품       금액
0     1  김민준  노트북  1200000
1     2  이서연  마우스    30000
2     3  박지훈  키보드    80000

## 5. 부서ID를 기준으로 두 DataFrame을 결합하여 다음과 같은 결과를 만드시오.

In [20]:
employee = pd.DataFrame({
    "사번": [101, 102, 103, 104],
    "이름": ["김민준", "이서연", "박지훈", "최유진"],
    "부서ID": [10, 20, 10, 30]
})

department = pd.DataFrame({
    "부서ID": [10, 20, 30],
    "부서명": ["개발팀", "인사팀", "영업팀"]
})

In [30]:
result3 = pd.merge(
    employee,
    department,
    on="부서ID",
    how="left",
)

result3

    사번   이름  부서ID  부서명
0  101  김민준    10  개발팀
1  102  이서연    20  인사팀
2  103  박지훈    10  개발팀
3  104  최유진    30  영업팀