In [1]:
import pandas as pd

In [37]:
data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [85, None, 90, 75, None],
    "출석": [True, True, None, True, False]
}

df = pd.DataFrame(data)

print(df) # 데이터프레임은 객체타입은 None, 숫자타입은 NaN으로 처리

print(df.isna())
# print(df.isnull())

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False
      이름     점수     출석
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [ ]:
df.isna().sum() # 결측치 개수 반환 X -> DataFrame.isna() 메서드
# 0 0 0 
# 0 1 0
# 0 0 1
# 0 0 0 
# 0 1 0

이름    0
점수    2
출석    1
dtype: int64

In [ ]:
df["점수"].isna() # Series.isna() 메서드

0    False
1     True
2    False
3    False
4     True
Name: 점수, dtype: bool

In [5]:
df

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False

In [7]:
# df[[False, True, False, False, True]]
df[df["점수"].isna()]

    이름  점수     출석
1  이서연 NaN   True
4  정현우 NaN  False

In [ ]:
cond = df["점수"].isna()
df[cond]

# df[조건식] df[size가 len(df)와 같은 bool배열]

    이름  점수     출석
1  이서연 NaN   True
4  정현우 NaN  False

In [15]:
# 0	김민준	85.0	True
# 1	이서연	NaN	True
# 2	박지훈	90.0	None
# 3	최유진	75.0	True
# 4	정현우	NaN	False

# df[[False, True, True, True, True]]
df[df["이름"] != "김민준"]

    이름    점수     출석
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False

In [12]:
df["이름"] != "김민준"

0    False
1     True
2     True
3     True
4     True
Name: 이름, dtype: bool

In [19]:
cond = df["점수"].isna() # [False, True, False, False, True] 시리즈 반환
print(df[cond]) # df[[False, True, False, False, True]] => True인 인덱스1, 4행 출력

print()

# 한줄의 코드로 만들면
print(df[df["점수"].isna()]) # df[조건] -> 행반환

print()

# cond가 True 이름만 출력 => loc[] 인덱스 사용
# []연산자 : 행 전체 or 열 전체
# loc[]인덱스 : 행 x 열 조합
print(df.loc[cond, "이름"]) # df[조건] -> 행반환
print(df.loc[df["점수"].isna(), "이름"]) # df[조건] -> 행반환

    이름  점수     출석
1  이서연 NaN   True
4  정현우 NaN  False

    이름  점수     출석
1  이서연 NaN   True
4  정현우 NaN  False

1    이서연
4    정현우
Name: 이름, dtype: str
1    이서연
4    정현우
Name: 이름, dtype: str

In [20]:
# 누락값 개수 확인
df.isna().sum()
# 이름    0 → 누락값 0개
# 점수    2 → 누락값 2개
# 출석    1 → 누락값 1개

이름    0
점수    2
출석    1
dtype: int64

In [22]:
# 결측치 대체
print(df.isna().any()) # 데이터프레임 열에 누락값이 하나라도 있으면 True

print()

print(df.isna().all()) # 데이터프레임 열이 모두 누락값이면 True

이름    False
점수     True
출석     True
dtype: bool

이름    False
점수    False
출석    False
dtype: bool

In [25]:
df

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False

In [24]:
# dropna() 누락값이 있는 행 삭제한 데이터프레임을 반환
df2 = df.dropna()
print(df2)

    이름    점수    출석
0  김민준  85.0  True
3  최유진  75.0  True

In [27]:
df3 = df.dropna(subset=["출석"])
df3

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
3  최유진  75.0   True
4  정현우   NaN  False

In [30]:
df4 = df.dropna(subset=["점수"])
df4

    이름    점수    출석
0  김민준  85.0  True
2  박지훈  90.0  None
3  최유진  75.0  True

In [31]:
df5 = df.dropna(subset=df.columns) # 기본값
df5

    이름    점수    출석
0  김민준  85.0  True
3  최유진  75.0  True

In [ ]:
df["점수"].fillna(100)

0     85.0
1    100.0
2     90.0
3     75.0
4    100.0
Name: 점수, dtype: float64

In [35]:
df2 = df
display(df)

df2["점수"] = df["점수"].fillna(100)
display(df2)

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False

    이름     점수     출석
0  김민준   85.0   True
1  이서연  100.0   True
2  박지훈   90.0   None
3  최유진   75.0   True
4  정현우  100.0  False

In [44]:
avg = df["점수"].mean()

In [45]:
df2 = df.copy()
df2

    이름    점수     출석
0  김민준  85.0   True
1  이서연   NaN   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우   NaN  False

In [46]:
df2["점수"] = df2["점수"].fillna(int(avg))
df2

    이름    점수     출석
0  김민준  85.0   True
1  이서연  83.0   True
2  박지훈  90.0   None
3  최유진  75.0   True
4  정현우  83.0  False

In [47]:
# 중앙값으로 대체

data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "점수": [85, None, 90, 75, None]
}

df = pd.DataFrame(data)

median_score = df["점수"].median()

# df["점수"] = df["점수"].fillna(df["점수"].median())
df["점수"] = df["점수"].fillna(median_score)

print(df)

    이름    점수
0  김민준  85.0
1  이서연  85.0
2  박지훈  90.0
3  최유진  75.0
4  정현우  85.0

In [51]:
# 범주(Category)의 경우 최빈값 대체

data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우"],
    "성별": ["M", "F", None, "F", None] 
}

df = pd.DataFrame(data)

gender = df["성별"].mode() # 최빈값
print(type(gender))

df["성별"].fillna(gender)
print(df["성별"].fillna(gender))

<class 'pandas.Series'>
0      M
1      F
2    NaN
3      F
4    NaN
Name: 성별, dtype: str

In [53]:
data = {
    "이름": ["김민준", "이서연", "박지훈", "최유진", "정현우", "정현우"],
    "성별": ["M", "F", None, "F", None, "M"] 
}

df = pd.DataFrame(data)

gender = df["성별"].mode() # 최빈값
print(type(gender))
print(gender)

# df["성별"].fillna(gender)
print(df["성별"].fillna(gender[0]))

<class 'pandas.Series'>
0    F
1    M
Name: 성별, dtype: str
0    M
1    F
2    F
3    F
4    F
5    M
Name: 성별, dtype: str

In [54]:
# mean(), ... min(), ...count()... 결측치 집계계산에 사용하지 않는다

df.count()

이름    6
성별    4
dtype: int64