In [1]:
import pandas as pd

In [ ]:
df = pd.DataFrame({"이름": ["김민준", "이서연", "박지훈"], 
                   "점수": [85, 90, 75]}, 
                   index=["가", "나", "다"])
# index 매개값 생략하면 Integer 위치값(iloc)과 동일한 index값을 기본값으로 생성
print(df)
df # 기본값 display(df)

    이름  점수
가  김민준  85
나  이서연  90
다  박지훈  75

    이름  점수
가  김민준  85
나  이서연  90
다  박지훈  75

In [9]:
df.columns # 열 인덱스

Index(['이름', '점수'], dtype='str')

In [ ]:
df.index # 행 인덱스

Index(['가', '나', '다'], dtype='str')

In [11]:
df.index.to_list()

['가', '나', '다']

In [12]:
df.index.name

In [15]:
df.index.name = "번호"
df

     이름  점수
번호
가   김민준  85
나   이서연  90
다   박지훈  75

In [16]:
df.index = [101, 200, 333]
df

      이름  점수
101  김민준  85
200  이서연  90
333  박지훈  75

In [18]:
# 인덱스 -> 열로 변경
df2 = df.reset_index()
df2

   index   이름  점수
0    101  김민준  85
1    200  이서연  90
2    333  박지훈  75

In [ ]:
# index -> 열
df.reset_index(inplace=True) # 기본값 False (원본변경 X)
df

   index   이름  점수
0    101  김민준  85
1    200  이서연  90
2    333  박지훈  75

In [20]:
# 열 -> 인덱스 set_index
df.set_index("index", inplace=True)
df

        이름  점수
index
101    김민준  85
200    이서연  90
333    박지훈  75