In [2]:
import pandas as pd

In [ ]:
# 1. 딕셔너리로 생성

# {레이블 : [], 레이블 : []}
df1 = pd.DataFrame({
    "이름" :["민수", "지영"],
    "점수" :[90, 85]
    })
# print() 터미널 출력
# display() 노트북 셀에 최적화 출력
df1

   이름  점수
0  민수  90
1  지영  85

In [ ]:
# 2. 리스트이 리스트로 생성 

# index값 행레이블(레이블 인덱스), columns값 열레이블(레이블 인덱스)
# 생략하면 위치값으로 기본값이 설정된다.

df2 = pd.DataFrame([
    ["민수", 90], # 1행
    ["지영", 100], # 2행
], index=["첫번째", "두번째"], columns=["이름", " 점수"])
df2

     이름   점수
첫번째  민수   90
두번째  지영   85

In [ ]:
# 3. 리스트의 딕셔너리로 생성

df3 = pd.DataFrame([
     {"이름":"민수", "점수":90}, # 1행
     {"이름":"지영", "점수":100}, # 2행
])
df3

   이름   점수
0  민수   90
1  지영  100

In [11]:
# 4. Numpy ndarray로 생성

import numpy as np

# numpy의 2차원 배열 - 모든 데이터 타입이 동일해야 함

df4 = pd.DataFrame(np.array([
    [1,2],
    [3,4],
]), columns=["x", "y"])

df4

   x  y
0  1  2
1  3  4

In [12]:
# 이름, 나이, 성별 데이터로 DataFrame 생성
df = pd.DataFrame({
    '이름': ['철수', '영희', '민수', '지영', '준호'],
    '나이': [20, 21, 20, 22, 21],
    '성별': ['남', '여', '남', '여', '남']
})

df

   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  민수  20  남
3  지영  22  여
4  준호  21  남

DataFrame 주요 속성

In [ ]:
# 1) 행 인덱스

df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
# 2) 열 이름

df.columns

Index(['이름', '나이', '성별'], dtype='str')

In [ ]:
# 3) 실제 값 배열

df.values # numpy의 array값으로 변환

array([['철수', 20, '남'],
       ['영희', 21, '여'],
       ['민수', 20, '남'],
       ['지영', 22, '여'],
       ['준호', 21, '남']], dtype=object)

In [ ]:
# 4) 열별 데이터 타입

df.dtypes  # 반환값 Series타입 index=Columns

이름      str
나이    int64
성별      str
dtype: object

In [ ]:
# 5~7) (행, 열) / 전체 원소 개수 / 차원 수

print(df.shape, df.size, df.ndim)

(5, 3) 15 2

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      5 non-null      str
 1   나이      5 non-null      int64
 2   성별      5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [ ]:
# 저장 단위

# KB -> MB -> GB -> TB -> PB -> ( EB -> ZB -> YB -> RB -> QB )

In [19]:
df.head(2)

   이름  나이 성별
0  철수  20  남
1  영희  21  여

In [20]:
df.tail(2)

   이름  나이 성별
3  지영  22  여
4  준호  21  남

In [ ]:
df.head() # 기본값 : 5

In [ ]:
# [] 인덱싱 연산자의 매개값 : index 사용(열 레이블, 표현식)

df["성별"]
# df["성별"].unique() -> sql select distinct (중복 제거)

0    남
1    여
2    남
3    여
4    남
Name: 성별, dtype: str

In [ ]:
df["성별"].nunique() # 범주값의 종류

2