## sklearn의 KBinsDiscretizer클래스를 이용한 이산화 실습

In [ ]:
import pandas as pd
from sklearn.preprocessing import KBinsDiscretizer

# 데이터
df = pd.DataFrame({
    "나이": [15, 23, 35, 47, 62]
})

display(df)

# 이산화
kb = KBinsDiscretizer(
    n_bins=3,              # 3개 구간
    encode="ordinal",      
    strategy="uniform"    
)


df["나이_구간"] = kb.fit_transform(df[["나이"]])

display(df)

   나이
0  15
1  23
2  35
3  47
4  62

   나이  나이_구간
0  15    0.0
1  23    0.0
2  35    1.0
3  47    2.0
4  62    2.0